#!/usr/bin/env python3
"""
athena.cli.init
===============

Scaffold a new Athena workspace with directory structure and templates.
Fulfills the "5-Minute Quickstart" promise.

Usage:
    athena init .                     # Initialize in current directory
    athena init --here                # Same as above
    athena init --here --ide cursor   # Init with Cursor-specific config
    athena init my-project            # Create new project directory
"""

import shutil
from datetime import datetime
from pathlib import Path

# Athena package root (for locating examples/ to copy into workspaces)
_ATHENA_PKG_ROOT = Path(__file__).resolve().parents[3]
_EXAMPLES_SCRIPTS = _ATHENA_PKG_ROOT / "examples" / "scripts"
_EXAMPLES_TEMPLATES = _ATHENA_PKG_ROOT / "examples" / "templates"

# Boot-critical scripts that must exist in .agent/scripts/ for `athena` to run
_BOOT_SCRIPTS = [
    "create_session.py",      # CRITICAL: session creation (sys.exit on failure)
    "compact_context.py",     # HIGH: auto-compaction when token budget exceeded
    "semantic_audit.py",      # OPTIONAL: audit reset on boot
    "smart_search.py",        # OPTIONAL: semantic priming
]

# Memory bank templates to copy into .context/memory_bank/
_MEMORY_BANK_FILES = [
    "activeContext.md",
    "userContext.md",
    "productContext.md",
]

# Framework mirror files to copy into .framework/modules/
_FRAMEWORK_MODULES = [
    "Core_Identity.md",       # CRITICAL: verified by SHA-384 at boot
    "Athena_Profile.md",      # OPTIONAL: cognitive profile display
]


# --- Templates ---

CORE_IDENTITY_TEMPLATE = """# Core Identity

> **Created**: {date}

## Who Am I?
An adaptive AI assistant — your strategic co-pilot, not just a chatbot.

## Operating Principles

1. **Memory First**: Log everything. Context is power.
2. **Proactive**: Anticipate needs, don't just react.
3. **Honest**: Challenge flawed assumptions respectfully.
4. **Modular**: One skill = one file. No monoliths.

## Reasoning Standards

- Consider 3+ perspectives before concluding
- Label assumptions explicitly
- Prioritize signal over noise
- Ask clarifying questions when uncertain

## Success Metric

A good conversation contains mutual corrections.
- I challenge your assumptions → you evaluate
- You correct my errors → I improve
- Both get sharper
"""

START_WORKFLOW_TEMPLATE = """---
description: Boot the AI assistant with context
---

# /start — Execution Script

> **Automation**: This workflow runs the Athena SDK boot sequence.

## Execution

// turbo

```bash
athena
```

The boot sequence will:
1. Load Core Identity
2. Recall last session context
3. Create a new session log
4. Confirm ready status

## Manual Override (if SDK unavailable)

- [ ] Read `.framework/modules/Core_Identity.md`
- [ ] Find the latest session log in `.context/memories/session_logs/`
- [ ] Create a new session log: `YYYY-MM-DD-session-XX.md`
- [ ] Output: "⚡ Ready. (Session XX started.)"
"""

END_WORKFLOW_TEMPLATE = """---
description: Close session and save learnings
---

# /end — Session Close

> **Automation**: This workflow runs the Athena SDK shutdown sequence.

## Execution

// turbo

```bash
athena --end
```

The shutdown sequence will:
1. Close the current session log
2. Update session status to "Closed"
3. Optionally trigger Supabase sync

## Manual Override (if SDK unavailable)

- [ ] Read all `### ⚡ Checkpoint` entries from current session log
- [ ] Fill in Key Topics, Decisions Made, Action Items
- [ ] Git add and commit the session log
- [ ] Output: "✅ Session XX closed and committed."
"""

SAVE_WORKFLOW_TEMPLATE = """---
description: Save a checkpoint to the current session
---

# /save — Quicksave Checkpoint

> **Automation**: This workflow runs the Athena SDK save command.

## Execution

// turbo

```bash
athena save "Brief summary of what happened"
```

The save command will append a timestamped checkpoint to the current session log.
"""


PROJECT_STATE_TEMPLATE = """---
created: '{date}'
last_updated: '2026-02-06'
framework_version: v1.0.0
---

# Project State (Single Source of Truth)

## 1. System Status

- **Health**: 100%
- **Session Count**: 0
- **Last Session**: None

## 2. Recent Changes

- [{date}] Initialized Athena workspace via `athena init`.

## 3. Notes

_Add project-specific notes here._
"""

# --- IDE-Specific Templates ---

ANTIGRAVITY_RULES = """# Antigravity Agent Rules

> Auto-generated by `athena init --ide antigravity`

## Boot Sequence
On `/start`, run: `athena`

## Save Sequence  
On `/end`, run: `athena --end`

## Quicksave
On `/save`, run: `athena save "summary"`

## Directory Context
- `.framework/` — Core identity and laws
- `.context/` — Session logs and memories  
- `.agent/` — Workflows and scripts
"""

CURSOR_RULES = """# Cursor Agent Rules

> Auto-generated by `athena init --ide cursor`

## Context

You are an AI agent operating within an Athena workspace.
Always check `.framework/modules/Core_Identity.md` for your operating principles.

## Key Directories

- `.framework/` — Your identity and laws (read this first)
- `.context/` — Session logs (check for prior context)
- `.agent/workflows/` — Available commands (start.md, end.md, save.md)

## Boot Command

Run `athena` to boot the session system, or manually read the latest session log.

## Session Discipline

1. On session start — run `/start` workflow
2. During work — periodically run `/save` to checkpoint
3. On session end — run `/end` workflow
"""

VSCODE_SETTINGS = """{
  "files.associations": {
    "*.md": "markdown"
  },
  "editor.wordWrap": "on",
  "files.exclude": {
    "**/__pycache__": true,
    "**/*.pyc": true
  },
  "markdown.preview.breaks": true
}
"""

GEMINI_RULES = """# Gemini Agent Rules

> Auto-generated by `athena init --ide gemini`

## Athena Workspace Context

This is an Athena workspace. Key directories:
- `.framework/` — Core identity, read `.framework/modules/Core_Identity.md` first
- `.context/` — Session logs and project state
- `.agent/` — Workflows and automation scripts

## Session Commands

| Command | Action |
|---------|--------|
| `athena` | Boot session |
| `athena save "note"` | Quicksave |
| `athena --end` | Close session |
| `athena check` | Health check |
"""


def init_workspace(target_dir: Path = None, ide: str = None) -> bool:
    """
    Initialize an Athena workspace with the required directory structure.

    Args:
        target_dir: Directory to initialize. Defaults to current directory.
        ide: IDE to generate config for (antigravity, cursor, vscode, gemini).

    Returns:
        True if successful, False otherwise.
    """
    root = target_dir or Path.cwd()
    root = Path(root).resolve()

    print("🏛️  ATHENA INIT")

    if ide:
        print(f"   IDE: {ide}")
    print("=" * 60)

    # Define structure
    directories = [
        ".agent/workflows",
        ".agent/scripts",
        ".agent/skills/protocols",
        ".agent/state",
        ".framework/modules",
        ".context/memories/session_logs",
        ".context/memory_bank",
        ".context/data",
    ]

    # Create directories
    print("\n📁 Creating directories...")
    for dir_path in directories:
        full_path = root / dir_path
        full_path.mkdir(parents=True, exist_ok=True)
        print(f"   ✅ {dir_path}/")

    # Create root marker (for path discovery)
    marker_path = root / ".athena_root"
    marker_path.write_text(f"# Athena Workspace\nCreated: {datetime.now().isoformat()}\n")
    print("   ✅ .athena_root (workspace marker)")

    # Create template files (inline content)
    today = datetime.now().strftime("%Y-%m-%d")

    templates = [
        (".agent/workflows/start.md", START_WORKFLOW_TEMPLATE),
        (".agent/workflows/end.md", END_WORKFLOW_TEMPLATE),
        (".agent/workflows/save.md", SAVE_WORKFLOW_TEMPLATE),
        (
            ".context/project_state.md",
            PROJECT_STATE_TEMPLATE.format(date=today),
        ),
    ]

    print("\n📝 Creating template files...")
    for file_path, content in templates:
        full_path = root / file_path
        if not full_path.exists():
            full_path.write_text(content)
            print(f"   ✅ {file_path}")
        else:
            print(f"   ⏭️  {file_path} (already exists)")

    # Copy boot-critical files from Athena package examples/
    _copy_boot_files(root, today)

    # IDE-specific configuration
    if ide:
        print(f"\n⚙️  Creating {ide} configuration...")
        _create_ide_config(root, ide)

    # Summary
    print("\n" + "=" * 60)
    print("✅ ATHENA WORKSPACE INITIALIZED")
    print("=" * 60)
    print("\n🚀 Next steps:")
    print("   1. Open this folder in your AI IDE")
    print('   2. Type "/start" to boot your agent')
    print('   3. Work with your agent, then type "/end" to save')
    print("\n📚 Docs: https://github.com/[AUTHOR]87/Athena-Public")

    return True


def _copy_file(src: Path, dest: Path, label: str) -> None:
    """Copy a single file if it doesn't already exist in the workspace."""
    if dest.exists():
        print(f"   ⏭️  {label} (already exists)")
        return
    if not src.exists():
        print(f"   ⚠️  {label} (source not found, skipped)")
        return
    shutil.copy2(src, dest)
    print(f"   ✅ {label}")


def _copy_boot_files(root: Path, today: str) -> None:
    """Copy boot-critical scripts, framework modules, and memory bank templates."""
    if not _EXAMPLES_SCRIPTS.is_dir():
        print(f"\n⚠️  Cannot locate Athena examples/ directory.")
        print(f"   Expected: {_EXAMPLES_SCRIPTS}")
        print(f"   Boot scripts will not be copied. You may need to copy them manually.")
        # Fall back to inline Core_Identity template
        ci_fallback = root / ".framework" / "modules" / "Core_Identity.md"
        if not ci_fallback.exists():
            ci_fallback.write_text(CORE_IDENTITY_TEMPLATE.format(date=today))
            print(f"   ✅ .framework/modules/Core_Identity.md (fallback template)")
        return

    # 1. Boot scripts → .agent/scripts/
    print("\n📦 Copying boot scripts...")
    for script in _BOOT_SCRIPTS:
        src = _EXAMPLES_SCRIPTS / script
        dest = root / ".agent" / "scripts" / script
        _copy_file(src, dest, f".agent/scripts/{script}")

    # 2. Framework modules → .framework/modules/
    print("\n📦 Copying framework modules...")
    fw_src_dir = _EXAMPLES_TEMPLATES / "framework_mirror" / "v8.2-stable" / "modules"
    fw_dest_dir = root / ".framework" / "modules"
    if fw_src_dir.is_dir():
        for module in _FRAMEWORK_MODULES:
            src = fw_src_dir / module
            dest = fw_dest_dir / module
            _copy_file(src, dest, f".framework/modules/{module}")
    else:
        # Fall back to inline template for Core_Identity
        ci_fallback = fw_dest_dir / "Core_Identity.md"
        if not ci_fallback.exists():
            ci_fallback.write_text(CORE_IDENTITY_TEMPLATE.format(date=today))
            print(f"   ✅ .framework/modules/Core_Identity.md (fallback template)")

    # 3. Memory bank templates → .context/memory_bank/
    print("\n📦 Copying memory bank templates...")
    mb_src_dir = _EXAMPLES_TEMPLATES / "memory_bank"
    mb_dest_dir = root / ".context" / "memory_bank"
    if mb_src_dir.is_dir():
        for template in _MEMORY_BANK_FILES:
            src = mb_src_dir / template
            dest = mb_dest_dir / template
            _copy_file(src, dest, f".context/memory_bank/{template}")
    else:
        print(f"   ⚠️  Memory bank templates not found, skipped")


def _create_ide_config(root: Path, ide: str) -> None:
    """Create IDE-specific configuration files."""

    if ide == "antigravity":
        # Antigravity uses AGENTS.md convention
        agents_path = root / "AGENTS.md"
        if not agents_path.exists():
            agents_path.write_text(ANTIGRAVITY_RULES)
            print("   ✅ AGENTS.md (Antigravity rules)")
        else:
            print("   ⏭️  AGENTS.md (already exists)")

    elif ide == "claude":
        from athena.cli.init_claude import create_claude_config

        create_claude_config(root)

    elif ide == "cursor":
        # Cursor uses .cursorrules
        cursor_dir = root / ".cursor"
        cursor_dir.mkdir(exist_ok=True)
        rules_path = cursor_dir / "rules.md"
        if not rules_path.exists():
            rules_path.write_text(CURSOR_RULES)
            print("   ✅ .cursor/rules.md")
        else:
            print("   ⏭️  .cursor/rules.md (already exists)")

    elif ide == "vscode":
        # VS Code uses .vscode/settings.json
        vscode_dir = root / ".vscode"
        vscode_dir.mkdir(exist_ok=True)
        settings_path = vscode_dir / "settings.json"
        if not settings_path.exists():
            settings_path.write_text(VSCODE_SETTINGS)
            print("   ✅ .vscode/settings.json")
        else:
            print("   ⏭️  .vscode/settings.json (already exists)")

    elif ide == "gemini":
        # Gemini CLI uses AGENTS.md or .gemini/
        gemini_dir = root / ".gemini"
        gemini_dir.mkdir(exist_ok=True)
        rules_path = gemini_dir / "AGENTS.md"
        if not rules_path.exists():
            rules_path.write_text(GEMINI_RULES)
            print("   ✅ .gemini/AGENTS.md")
        else:
            print("   ⏭️  .gemini/AGENTS.md (already exists)")


if __name__ == "__main__":
    import sys

    target = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    init_workspace(target)
